### ISSUE TITLE
NRPE: Unable to read output 

### ISSUE THREAD

**Issue by azharkhn** [kjhosein/nagios-freeswitch-plugin#2]
When I execute plugin script directly, it works fine as blow:

```
# /usr/lib64/nagios/plugins/check_freeswitch_health -q show-calls-count                                                                                                                   
FREESWITCH_HEALTH OK - Result of check is: 0 total.  | show-calls-count=0;; 
```

But When I execute plugin with NRPE it doesn't work

```
# /usr/lib64/nagios/plugins/check_nrpe -H 46.101.86.250                                                                                                                                   
NRPE v2.15 
```

Rather gives me NRPE: Unable to read output 

```
# /usr/lib64/nagios/plugins/check_nrpe -H X.X.X.X-c check_freeswitch                                                                                                               
NRPE: Unable to read output 
```

It could be permissions issue but I have set 777 permissions to fs_cli and plugin script, still its not working.

Any help?

**Comment by kjhosein** [comment]
Hi @azharkhn - First, I bet it's just a typo in your last example code above, but you don't have a space after the X.X.X.X IP address and the command reads `check_freeswitch` instead of `check_freeswitch_health`.

But that aside, I think it's a permissions and/or rights issue. Take a look through [this Q&A](http://serverfault.com/questions/323233/nrpe-unable-to-read-output-but-why) which has various scenarios and answers.

**Comment by azharkhn** [comment]
There is no any typo as I am using following syntax for command

`command[check_freeswitch] = /usr/lib64/nagios/plugins/check_freeswitch_health.pl $ARG1$`

There must be some permissions issue that has been ignored by me.
